services:
  php:
    image: wodby/php:latest
    container_name: prog_m5_php
    volumes:
      - './:/var/www/html'

  nginx:
    image: nginx:latest
    container_name: prog_m5_nginx
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php

  groenekist:
    image: mysql:latest
    container_name: prog_m5_groenekist
    ports:    
      - "3306:3306"
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: prog_m5_phpmyadmin
    ports:
      - "8805:80"
    depends_on:
      - groenekist
    environment:
      PMA_HOST: '${DB_HOST}'
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
